version: '1'
services:
  web:
    image: 'frontend'
    build: .
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - database.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  backend:
    image: 'backend'
    restart: always
    env_file:
      - backend.env
    depends_on:
      - db

  loadbalancer:
    image: traefik
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - backend
      - frontend
      - loadbalancer

networks:
  loadbalancer:
  frontend:
  backend:
  db:

volumes:
  db-data:
    driver: local
