version: '1'
services:
  #web:
   # build: 'frontend'
    #depends_on:
     # - database

  database:
    image: 'postgres:latest'
    restart: always
    env_file:
      - database.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  backend:
    build: 'backend'
    restart: always
    env_file:
      - backend.env
    depends_on:
      - database

  loadbalancer:
    image: traefik
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - backend
      #- frontend
      - loadbalancer

networks:
  loadbalancer:
  #frontend:
  backend:
  database:

volumes:
  db-data:
    driver: local
