version: '1'
services:
  web:
    build: 'frontend'
    depends_on:
      - backend1
      - backend2
    ports:
      - 2022:2022

  database:
    image: 'postgres:latest'
    restart: always
    env_file:
      - database.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  backend1:
    build: 'backend'
    restart: always
    ports:
      - 8080:8080
    env_file:
      - backend.env
    depends_on:
      - database
  backend2:
    build: 'backend'
    restart: always
    env_file:
      - backend.env
    depends_on:
      - database

  loadbalancer:
    image: traefik:v2.9
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.yml:/etc/traefik/traefik.yml'
      - './traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml'
    command: --providers.docker.exposedbydefault=false --api.insecure=true 
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    

#    networks:
#      - backend
#      - frontend
#      - loadbalancer

#networks:
#  loadbalancer:
#  frontend:
#  backend:
#  database:

volumes:
  db-data:
    driver: local