http:
  routers:
    dashboard:
      rule: "PathPrefix(`/api`)"
      service:  svcBackend
      entrypoints:
        - "websecure"
      tls:
        domains:
          - main: "localhost"
    myservice:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - "websecure"
      service: svcfrontend
      tls:
        domains:
          - main: "localhost"
  services:
    svcfrontend:
      loadBalancer:
        servers:
          - url: "http://web:2022/"
    svcBackend:
      loadBalancer:
        healthCheck:
          path: /api/tasks
          interval: 5s
        servers:
          - url: "http://backend1:8080"
          - url: "http://backend2:8080"