http:
  routers:
    myservice:
      rule: "Host(`localhost`)"
      entrypoints:
        - "websecure"
      service: myservice
      tls:
        domains:
          - main: "localhost"
  services:
    myservice:
      loadBalancer:
        servers:
          - url: "http://web:2022/"
      

# tls:
#   certificates:
#     - certFile: "/etc/traefik/localhost+1.pem"
#       keyFile: "/etc/traefik/localhost+1-key.pem"