http:
  routers:
    dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/api/tasks`)"
      service:  mylbservice
    myservice:
      rule: "Host(`localhost`)"
      entrypoints:
        - "websecure"
      service: myservice
      tls:
        domains:
          - main: "localhost"
  services:
    myservice:
      loadBalancer:
        servers:
          - url: "http://web:2022/"
    mylbservice:
      loadBalancer:
        servers:
          - url: "http://backend1:8080"
          - url: "http://backend2:8080"
      

# tls:
#   certificates:
#     - certFile: "/etc/traefik/localhost+1.pem"
#       keyFile: "/etc/traefik/localhost+1-key.pem"